#!/bin/bash

echo ="Deploying CloudFormation stack: s3-iac-cnf"
aws cloudformation deploy \
    --template-file s3-iac-cnf.yaml \
    --stack-name s3-iac-cnf \
    --capabilities CAPABILITY_NAMED_IAM \
    --region us-east-1
